name : "terraform ci/cd"

on:
  push:
    branches:
      - main
      - test
      - dev
      # Add other branches if needed
  pull_request:
    branches:
      - main
      # Add other branches if needed
    Paths: './AWS-Terraform/**'

env:
  TF_LOG: INFO
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  # BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE}}

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  terraform-plan:
    name: terraform plan
    runs-on: ubuntu-latest
    outputs:
      tfplan-file: ${{ steps.set-tfplan-file.outputs.tfplan-file }}
    defaults:
      shell: bash
      working-directory: './AWS-Terraform/**'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.6

      - name: Terraform Init Tflint
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
        run: Tflint --init

      - name: TFLint
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
        run: Tflint -f compact

      - name: Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "config"
          format: table
          exit-code: '0'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true

